version: '3'

services:
###> doctrine/doctrine-bundle ###
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    command: [ "php-fpm" ]
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: devo
    ports:
      - "3306:3306"
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "82:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - .:/app
    depends_on:
      - app
    restart: unless-stopped
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
